/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with this
 * work for additional information regarding copyright ownership. The ASF
 * licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

package org.apache.hugegraph.temporal.store;

import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Server-side assembler of the four temporal view mutations for one
 * {@link TemporalWrite.Request} (design ruling §3.2 step 2: "generate
 * current-view / history / open-interval-index / temporal-index mutations").
 *
 * <p>The four view NAMES are the frozen Server&lt;-&gt;Store wire contract and MUST
 * match the Store temporal table names ({@code HugeServerTables}); the Server
 * has no dependency on hg-store-common, so the names are kept as constants here
 * and equality is enforced by the Store-side wire protocol test. The four view
 * KEYS reuse the frozen {@link TemporalRowKeyCodec} and {@link TieBreakers}:
 * every suffix below {@code groupPrefix} is FIXED-WIDTH so the lexicographic
 * byte order equals the logical order (design ruling §2.1):</p>
 *
 * <ul>
 *   <li>history: {@code group | label | entity | fact_key_hash | time_bucket |
 *       valid_from | tie_breaker} via {@link TemporalRowKeyCodec#historyRowKey};</li>
 *   <li>current: {@code group_prefix || 0x43 || canonical_fact_key};</li>
 *   <li>open-interval index (open intervals only): {@code group_prefix || 0x4F
 *       || big-endian(valid_from) || tie_breaker};</li>
 *   <li>temporal index: {@code group_prefix || 0x49 || big-endian(valid_from)
 *       || tie_breaker}.</li>
 * </ul>
 *
 * <p>Scope: the plan covers the interval-creating operations APPEND and UPSERT.
 * CLOSE/DELETE mutate the current pointer and remove the open-index entry
 * (design ruling §3.2) and are generated by the close/delete state machine, a
 * later slice; this planner rejects them explicitly instead of emitting a wrong
 * interval view.</p>
 */
public final class TemporalMutationPlanner {

    // Must match org.apache.hugegraph.store.constant.HugeServerTables.
    public static final String HISTORY_VIEW = "g+temporal_history";
    public static final String CURRENT_VIEW = "g+temporal_current";
    public static final String OPEN_INDEX_VIEW = "g+temporal_open_index";
    public static final String INDEX_VIEW = "g+temporal_index";

    private static final byte CURRENT_MARKER = 0x43; // 'C'
    private static final byte OPEN_MARKER = 0x4F;    // 'O'
    private static final byte INDEX_MARKER = 0x49;   // 'I'

    private TemporalMutationPlanner() {
    }

    public static TemporalMutationPlan plan(TemporalWrite.Request request,
                                            TemporalRowKeyCodec codec) {
        if (request.operation() == TemporalWrite.Operation.CLOSE ||
            request.operation() == TemporalWrite.Operation.DELETE) {
            // close/delete mutate the current pointer and remove the open-index
            // entry (design ruling §3.2); they carry no interval views and are
            // applied by the close/delete state machine on the Store path.
            String tieBreaker = TieBreakers.derive(
                    request.mutationId(),
                    request.factKey().canonicalBytes(),
                    request.canonicalIntervalPayload());
            return new TemporalMutationPlan(request, tieBreaker,
                                            Collections.emptyList());
        }
        if (request.operation() != TemporalWrite.Operation.APPEND &&
            request.operation() != TemporalWrite.Operation.UPSERT) {
            throw new IllegalArgumentException(
                    "interval view generation is defined only for APPEND/UPSERT; " +
                    request.operation() + " is generated by the close/delete state machine");
        }

        String tieBreaker = TieBreakers.derive(
                request.mutationId(),
                request.factKey().canonicalBytes(),
                request.canonicalIntervalPayload());
        byte[] prefix = codec.groupPrefix(request.graphId(), request.temporalLabel(),
                                          request.entityId(), request.factKey());

        List<TemporalMutationPlan.ViewKey> views = new ArrayList<>(4);
        views.add(new TemporalMutationPlan.ViewKey(HISTORY_VIEW,
                codec.historyRowKey(request.graphId(), request.temporalLabel(),
                                    request.entityId(), request.factKey(),
                                    request.validFrom(), tieBreaker)));
        views.add(new TemporalMutationPlan.ViewKey(CURRENT_VIEW,
                append(prefix, new byte[]{CURRENT_MARKER},
                       request.factKey().canonicalBytes())));
        if (request.validTo() == null) {
            views.add(new TemporalMutationPlan.ViewKey(OPEN_INDEX_VIEW,
                    indexKey(prefix, OPEN_MARKER, request.validFrom(), tieBreaker)));
        }
        views.add(new TemporalMutationPlan.ViewKey(INDEX_VIEW,
                indexKey(prefix, INDEX_MARKER, request.validFrom(), tieBreaker)));

        return new TemporalMutationPlan(request, tieBreaker, views);
    }

    private static byte[] indexKey(byte[] prefix, byte marker, long validFrom,
                                   String tieBreaker) {
        return append(prefix, new byte[]{marker}, bigEndianLong(validFrom),
                      tieBreaker.getBytes(StandardCharsets.US_ASCII));
    }

    /** Fixed-width byte concatenation (no length prefixes, sortable). */
    private static byte[] append(byte[]... parts) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        for (byte[] part : parts) {
            out.write(part, 0, part.length);
        }
        return out.toByteArray();
    }

    /** Big-endian long, fixed width, lexicographic order equals numeric order. */
    private static byte[] bigEndianLong(long v) {
        byte[] out = new byte[8];
        for (int i = 7; i >= 0; i--) {
            out[7 - i] = (byte) ((v >>> (i * 8)) & 0xFF);
        }
        return out;
    }
}
